from __future__ import annotations

from typing import Protocol

from core.attention.actions.models import ActionPlan, ActionPlanStatus
from core.attention.feedback.models import AttentionFeedback
from core.attention.events import CanonicalEntity, CanonicalEvent, EventStatus, WakePlan
from core.attention.learning.models import AttentionObservation
from core.attention.opportunities import OpportunityWindow
from core.attention.patterns import BehaviorPattern
from core.attention.policies import PolicyRule
from core.attention.signals import AttentionSignal


class AttentionRepository(Protocol):
    def upsert_signal(self, signal: AttentionSignal) -> AttentionSignal: ...
    def upsert_signals(
        self,
        signals: list[AttentionSignal],
    ) -> list[AttentionSignal]: ...
    def get_signal(self, signal_id: str) -> AttentionSignal | None: ...
    def list_active_signals(self, *, now) -> list[AttentionSignal]: ...

    def upsert_pattern(self, pattern: BehaviorPattern) -> BehaviorPattern: ...
    def get_pattern(self, pattern_id: str) -> BehaviorPattern | None: ...
    def list_patterns(self) -> list[BehaviorPattern]: ...

    def upsert_window(self, window: OpportunityWindow) -> OpportunityWindow: ...
    def upsert_windows(
        self,
        windows: list[OpportunityWindow],
    ) -> list[OpportunityWindow]: ...
    def get_window(self, window_id: str) -> OpportunityWindow | None: ...
    def list_active_windows(self, *, now) -> list[OpportunityWindow]: ...

    def upsert_policy(self, policy: PolicyRule) -> PolicyRule: ...
    def get_policy(self, policy_id: str) -> PolicyRule | None: ...
    def list_policies(self) -> list[PolicyRule]: ...

    def add_observation(self, observation: AttentionObservation) -> bool: ...
    def list_observations(self, *, limit: int = 100) -> list[AttentionObservation]: ...

    def create_plan(self, plan: ActionPlan) -> ActionPlan: ...
    def get_plan(self, plan_id: str) -> ActionPlan | None: ...
    def find_plan_by_key(self, idempotency_key: str) -> ActionPlan | None: ...
    def list_plans(self, *, limit: int = 100) -> list[ActionPlan]: ...
    def transition_plan(
        self,
        plan_id: str,
        status: ActionPlanStatus,
        *,
        result: dict | None = None,
        error: str = "",
    ) -> ActionPlan: ...

    def add_feedback(self, feedback: AttentionFeedback) -> AttentionFeedback: ...
    def list_feedback(
        self,
        *,
        plan_id: str | None = None,
    ) -> list[AttentionFeedback]: ...

    def upsert_entity(self, entity: CanonicalEntity) -> CanonicalEntity: ...
    def get_entity(self, entity_id: str) -> CanonicalEntity | None: ...
    def list_entities(self, *, limit: int = 1000) -> list[CanonicalEntity]: ...
    def upsert_event(self, event: CanonicalEvent) -> CanonicalEvent: ...
    def get_event(self, event_id: str) -> CanonicalEvent | None: ...
    def list_active_events(self) -> list[CanonicalEvent]: ...
    def upsert_wake(self, wake: WakePlan) -> WakePlan: ...
    def get_wake(self, wake_id: str) -> WakePlan | None: ...
    def list_pending_wakes(self) -> list[WakePlan]: ...
    def next_wake_at(self) -> str | None: ...
    def claim_due_wakes(self, *, now, limit: int = 20) -> list[WakePlan]: ...
    def recover_processing_wakes(self) -> int: ...
    def complete_wake(self, wake_id: str, *, decision: str) -> WakePlan: ...
    def defer_wake(self, wake_id: str, *, wake_at, decision: str) -> WakePlan: ...
    def close_event(self, event_id: str, status: EventStatus) -> CanonicalEvent: ...
    def close_events_for_entity(
        self,
        entity_id: str,
        status: EventStatus,
    ) -> list[CanonicalEvent]: ...

    def close(self) -> None: ...


__all__ = ["AttentionRepository"]
